### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by michealcell** [AshitaXI/Ashita#38]
I get the error Too Many Open Files randomly about 3-5 times daily for different addons, such as minimap, mobdb, luashitacast, etc.

![Screenshot 2023-04-05 090625](https://user-images.githubusercontent.com/52577368/230246512-0ffa8862-74d5-4e7f-8e15-2979cfef3b35.png)

**Comment by Shirk** [comment]
First time seeing that one even for horizon, can you provide a list of all addons and plugins you are using with v4 as well as any extra tools you are running on your system? Does it also happen if you shutdown anything else you might be running besides the game?

**Comment by michealcell** [comment]
![Screenshot 2023-04-07 202022](https://user-images.githubusercontent.com/52577368/230695130-5bc768e1-ab99-43c2-af41-7d71280a7f8a.png)

Got it today, I closed down almost all my programs. I had up Discord, Steam, Telegram, Razer's thing, and Chrome. As for addon's, my list is: 
/load addons
/load screenshot
/load Minimap
/load PacketFlow
/load thirdparty
/addon load dynamic_entity_renamer
/addon load allmaps
/addon load aspect
/addon load Checker
/addon load drawdistance
/addon load enternity
/addon load fps
/addon load instantah
/addon load macrofix
/addon load timers
/addon load hxui
/addon load noname
/addon load chains
/addon load fastcs
/addon load luashitacast
/addon load mobdb
/addon load debuff

**Comment by atom0s** [comment]
Responded to this on Discord but will also reiterate the issue here. 'Too many open files' is due to the process hitting the open handle resource limit of Windows. This happens when the process has not properly free'd resources that cause a handle to remain open. This could be things such as opening a file (ie. fopen, CreateFile, etc.) or creating objects such as DIB sections, brushes, or other similar kinds of resources.

The following is what I could find in the above list of addons/plugins with minimal time to actually dig into things, so there could be other leaks that I missed:

  - `debuff` - The user that reported this has a modified version of this addon that is leaking, the original/default is fine.

  - `fisherlogs` - JB
    - Pretty much every `io.open` instance in this addon can leak due to how its coded. This addon is not really coded properly/well to handle file usage.

  - `mobdb` - @ThornyFFXI
    - https://github.com/ThornyFFXI/mobdb/blob/main/addons/mobdb/import_custom.lua#L312 - `dat` is not properly cleaned up.
    - https://github.com/ThornyFFXI/mobdb/blob/main/addons/mobdb/import_lsb.lua#L312 - `dat` is not properly cleaned up.
    - https://github.com/ThornyFFXI/mobdb/blob/main/addons/mobdb/import_wings.lua#L312 - `dat` is not properly cleaned up.

  - `simplelog` - @Spike2D
    - https://github.com/Spike2D/SimpleLog/blob/main/lib/shift_jis.lua#L57 - `f2` is not properly cleaned up.

**Comment by atom0s** [comment]
Given that these issues are not with Ashita itself, but with addons/plugins that are from thirdparty things, I am going to close this issue.
