### ISSUE TITLE
Is it possible to copy the game text to the clipboard to make automatic translations?

### ISSUE THREAD

**Issue by Cloudstrifeff7** [AshitaXI/Ashita#49]
Good morning, I don't know if the request is right but I apologize in advance in case I am doing it wrong.
I am asking if it is possible an addon/plugin that takes the text of the game as it appears to put it for example in the clipboard, so as to use external programs that automatically translate the text in the clipboard to other languages. For example there is something similar for Elder Scrolls Online that at each dialog the text goes into the clipboard and an external program automatically translates all the text that comes into the clipboard.
Something amazing there is for Final Fantasy XIV that automatically takes care of translating the text into the desired language and it is this: https://github.com/NightlyRevenger/TataruHelper

I have never played Final Fantasy XI and would like to start it by understanding the plot as best I can since I am not very good at English. I don't necessarily want something complex like TataruHelper, but if there is a possibility to create an addon/plugin that simply takes the text whenever it appears in game (from dialogues) and puts it in the clipboard would be of great help to me.
Thank you very much in advance!

**Comment by atom0s** [comment]
Hello there. Something like this is entirely possible but I'd suggest doing it in a different manner. Since we are fully injected into the game, we have an advantage of being able to see all incoming and outgoing text being processed through the client. This means there's no reason or need to use/rely on the clipboard to do something like this. 

Instead, you can use Ashita's text events to capture the text and translate it as you wish then output it either back into the client itself, into a custom rendered element in-game or dump it / send it somewhere else to be displayed outside of the client.

For addons, the two event's of interest would be:

  - `text_in`
  - `text_out`

The same events for plugins are:

  - `HandleIncomingText`
  - `HandleOutgoingText`

This is not something we would likely work on ourselves and would be better suited for a thirdparty to work on it or assist you with it.
You can ask for help with writing an addon/plugin on our Discord https://discord.gg/Ashita

**Comment by Cloudstrifeff7** [comment]
> Hello there. Something like this is entirely possible but I'd suggest doing it in a different manner. Since we are fully injected into the game, we have an advantage of being able to see all incoming and outgoing text being processed through the client. This means there's no reason or need to use/rely on the clipboard to do something like this.
> 
> Instead, you can use Ashita's text events to capture the text and translate it as you wish then output it either back into the client itself, into a custom rendered element in-game or dump it / send it somewhere else to be displayed outside of the client.
> 
> For addons, the two event's of interest would be:
> 
> * `text_in`
> * `text_out`
> 
> The same events for plugins are:
> 
> * `HandleIncomingText`
> * `HandleOutgoingText`
> 
> This is not something we would likely work on ourselves and would be better suited for a thirdparty to work on it or assist you with it. You can ask for help with writing an addon/plugin on our Discord https://discord.gg/Ashita

Thank you very much for your reply! I will try to ask in the discord! :D

**Comment by atom0s** [comment]
I'd recommend v4 as we no longer are updating/working on v3.

I'll close this issue as well since this is something better suited for the Discord. :)
