### ISSUE TITLE
Constants to avoid magic numbers

### ISSUE THREAD

**Issue by paige404** [AshitaXI/Ashita#6]
Looking over existing addons for v3 I see them littered with magic numbers everywhere. Even in the example addon for v4, it's full of them.

[Here is a good example](https://github.com/AshitaXI/example/blob/main/example.lua#L389):
```lua
if (e.id == 0x5D) then
    -- Look for /panic emotes and replace them with /wave instead.. (All via FFI)
    local ffi = require('ffi');
    local ptr = ffi.cast('uint8_t*', e.data_modified_raw);

    -- Replace the emote..
    if (ptr[0x0A] == 29) then
        ptr[0x0A] = 8;
    end        
end
```
If not for the comment above telling me what `0x5D` meant, I would have no idea. As a software engineer new to developing addons for Ashita, this gives me pause. I imagine many people have had an interest in developing addons, seen the sheer amount of unexplained hexcodes in existing addons, and backed away slowly.

So why not introduce constants for this? Rather than `0x5D`, `packets.EMOTE`? These kinds of features and obfuscations have helped FFXIV's Dalamud plugin library to flourish with new development.

**Comment by atom0s** [comment]
While this may come off as 'harsh' it's mainly just how we have always gone with Ashita's open development side of things with addons/plugins. If you don't know how to read packets or figure out what their data is, or how their IDs relate to something, it's usually best that you don't touch them to begin with. 

We've always preferred and encouraged developers to use our SDK/API over packets whenever possible because of a few factors:

 - It lessens the chances of your addon/plugin breaking in the future.
 - It lessens the downtime of your addon/plugin if it does break in the future as our SDK would generally only need to be updated to fix it.
 - It lessens the chance of account bans by someone, who does not know what they're doing with packets, doing something incorrectly and making things happen that shouldn't.

And so on.

v4 may eventually have a more solidified packet helper/header. But for the time being those of us that do work with the packet sides of things don't have a need for it or really care that one isn't established. And it helps deter the over-usage of things that don't need it.

In the mean time, there are other references you can use, but keep in mind they are not 100% accurate/correct and can lead to bad things if used imporperly:

 - https://wiki.dspt.info/index.php/Packet_IDs
 - https://github.com/Windower/Lua/blob/dev/addons/libs/packets/fields.lua
