### ISSUE TITLE
Items don’t load game crashes when I click on items

### ISSUE THREAD

**Issue by AfroKnightMan** [AshitaXI/Ashita#62]
![image](https://github.com/user-attachments/assets/1d8bdd8e-6284-4829-be8d-0d5ec7760565)
**Ashita Version** _(Type /ashita in-game to get this.)_

**FFXI Version** _(Type /version in-game to get this.)_

**Windows Version** _(ie. Start > About Your PC)_
I have window 11

**Describe The Bug*
Please give a clear, full description of the bug.
Every time I go to items it crashes. also mog is not here. 
**Steps To Reproduce**
Please give a clear, full list of steps to reproduce the bug, if applicable. 

**Screenshots**
Now this I see “Enable debug mode logging for more details ” I don’t know really much. 

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.
Any clue?

**Comment by bliven-was-taken** [comment]
This looks like you are playing on a private server and didn't update your game in the launcher as required.

**Comment by atom0s** [comment]
This does not sound like an issue with Ashita, but rather issue(s) with your installation and/or DAT file modifications.

- Crashing due to opening your inventory and looking at an item is generally due to bad DAT files related to the new icon added to show items that can be delivered between characters on your account. It can also be due to bad/corrupted item DATs causing the game to fail loading any of the item information in general.
- Missing Moogle sounds like your installation is incomplete or has corrupted files causing models to not load.

This does not sound like any of these issues are actually Ashita's fault. I would suggest you contact the staff of the server you are playing on for assistance with your installation. We do not give support for private servers individual installs or modifications to the games files. If you are playing on retail, then I would suggest reinstalling the game.
