### ISSUE TITLE
[BUG] doesnt work for mules only main character

### ISSUE THREAD

**Issue by leelightfoot25** [AshitaXI/Ashita#65]
**Ashita Version** _(Type /ashita in-game to get this.)_
4.2.0.3

**FFXI Version** _(Type /version in-game to get this.)_
this didnt work typing /version in game didnt seem to do anything

**Windows Version** _(ie. Start > About Your PC)_
Edition	Windows 11 Pro
Version	24H2
Installed on	‎10/‎26/‎2024
OS build	26100.2161
Experience	Windows Feature Experience Pack 1000.26100.32.0

**Describe The Bug**
recast doesnt show up for ether of my non primary characters
I have tried unloading / reloading recast.  it says recast is unloaded, then it says reloaded, but when casting spells i dont get any of the UI that i do when i'm on my primary 1st character. 

**Steps To Reproduce**
I have tried unloading / reloading recast.  it says recast is unloaded, then it says reloaded, but when casting spells i dont get any of the UI that i do when i'm on my primary 1st character. 

**Screenshots**

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.

**Comment by atom0s** [comment]
Hello, this is likely due to Recast having invalid settings for the other characters. You can try removing any already created settings for those mules by doing the following:

If you are in-game then please do the following first:

  - Unload the recast addon via: `/addon unload recast`

Next, open the following folder:

  - `<Path To Ashita>/config/addons/recast/`

Locate the folders that contain the names of your mules and delete them. Afterward, reload the recast addon and see if it shows up properly.

**Comment by leelightfoot25** [comment]
It's unclear to me why that worked because none of the folders existed
prior to me logging in.

They did appear once I logged in and I followed your steps to the letter
and now it appears that for all three characters but the mules. Most
importantly, it appears to be continuing to work after logouts or
shutdowns.
Thank you very much for being so responsive.

**Comment by leelightfoot25** [comment]
I was using speech to text there. I'm not sure why it says but the mules.
It is working for all three characters at this moment.

Thank you so much!.
